steps:
  # --- Build Services ---


  # --- Build Ingestion Pipelines ---
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Google Ads Ingestion Pipeline'
    args: ['build', '-t', 'gcr.io/annular-net-436607-t0/google_ads_ingestion', './pipelines/google_ads_ingestion']
    waitFor: ['-']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Google Ads Ingestion Pipeline'
    args: ['push', 'gcr.io/annular-net-436607-t0/google_ads_ingestion']
    waitFor: ['Build Google Ads Ingestion Pipeline']

  # # --- Build dbt Pipelines ---
  # - name: 'gcr.io/cloud-builders/docker'
  #   id: 'Build dbt for Google Ads Pipeline'
  #   args: ['build', '-t', 'gcr.io/annular-net-436607-t0/dbt_google_ads_pipeline', './dbt/google_ads_dbt']
  #   waitFor: ['-']

  # - name: 'gcr.io/cloud-builders/docker'
  #   id: 'Push dbt for Google Ads Pipeline'
  #   args: ['push', 'gcr.io/annular-net-436607-t0/dbt_google_ads_pipeline']
  #   waitFor: ['Build dbt for Google Ads Pipeline']

  # --- Deploy Pipelines to Cloud Run ---
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Deploy Google Ads Ingestion Pipeline'
    args:
      - 'run'
      - 'deploy'
      - 'google-ads-ingestion'
      - '--image'
      - 'gcr.io/annular-net-436607-t0/google_ads_ingestion'
      - '--platform'
      - 'managed'
      - '--region'
      - 'europe-west1'
      - '--service-account'
      - 'terraform-sa@annular-net-436607-t0.iam.gserviceaccount.com'
      - '--allow-unauthenticated'
      - '--set-env-vars' 
      - 'ENV=dev'
      - '--set-env-vars' 
      - 'PROJECT_ID=annular-net-436607-t0'
      - '--set-env-vars' 
      - 'DATASET_ID_DEV=sample_ds'
      - '--set-env-vars' 
      - 'DATASET_ID_PROD=ggg'
      - '--set-env-vars' 
      - 'RAW_TABLE_ID_DEV=raw_google_ads_dev'
      - '--set-env-vars' 
      - 'RAW_TABLE_ID_PROD=raw_google_ads_prod'
      - '--set-env-vars'
      - 'ADVERTISERS_TRACKING_TABLE_ID_DEV=advertisers_tracking_dev'
      - '--set-env-vars'
      - 'ADVERTISERS_TRACKING_TABLE_ID_PROD=advertisers_tracking_prod'
    waitFor: ['Build Google Ads Ingestion Pipeline']



  # --- Deploy Services to Cloud Run ---

  # # --- Deploy dbt Pipelines to Cloud Run ---
  # - name: 'gcr.io/cloud-builders/gcloud'
  #   id: 'Deploy dbt Google Ads Pipeline'
  #   args:
  #     - 'run'
  #     - 'deploy'
  #     - 'dbt-google-ads-pipeline'
  #     - '--image'
  #     - 'gcr.io/annular-net-436607-t0/dbt_google_ads_pipeline'
  #     - '--platform'
  #     - 'managed'
  #     - '--region'
  #     - 'europe-west1'
  #     - '--service-account'
  #     - 'terraform-sa@annular-net-436607-t0.iam.gserviceaccount.com'
  #     - '--allow-unauthenticated'
  #   waitFor: ['Build dbt for Google Ads Pipeline']

# For getting prohect only 
# substitutions:
#   _ENVIRONMENT: 'dev'   # Can be overridden by Cloud Build triggers for different environments
#   _PROJECT_ID: 'annular-net-436607-t0'

logsBucket: 'gs://annular-net-436607-t0-cloudbuild-logs'
serviceAccount: 'projects/annular-net-436607-t0/serviceAccounts/terraform-sa@annular-net-436607-t0.iam.gserviceaccount.com'

# Specify the images to be stored in Google Container Registry
images:
  - 'gcr.io/$PROJECT_ID/google_ads_ingestion'
  # - 'gcr.io/annular-net-436607-t0/dbt_google_ads_pipeline'
