steps:
  # --- Build Services ---
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build login service'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/login_service', './services/login_service']
    waitFor: ['-']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build ads data service'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/ads_data_service', './services/ads_data_service']
    waitFor: ['-']

  # --- Build Ingestion Pipelines ---
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Meta Ingestion Pipeline'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/meta_ingestion', './pipelines/meta_ingestion']
    waitFor: ['-']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Google Ads Ingestion Pipeline'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/google_ads_ingestion', './pipelines/google_ads_ingestion']
    waitFor: ['-']

  # --- Build dbt Pipelines ---
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build dbt for Meta Pipeline'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/dbt_meta_pipeline', './dbt/meta_dbt']
    waitFor: ['-']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build dbt for Google Ads Pipeline'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/dbt_google_ads_pipeline', './dbt/google_ads_dbt']
    waitFor: ['-']

  # --- Deploy Services to Cloud Run ---
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy login service'
    args:
      - run
      - deploy
      - 'login-service'
      - '--image'
      - 'gcr.io/$PROJECT_ID/login_service'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
    waitFor: ['Build login service']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy ads data service'
    args:
      - run
      - deploy
      - 'ads-data-service'
      - '--image'
      - 'gcr.io/$PROJECT_ID/ads_data_service'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
    waitFor: ['Build ads data service']

  # --- Deploy dbt Pipelines to Cloud Run ---
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy dbt Meta Pipeline'
    args:
      - run
      - deploy
      - 'dbt-meta-pipeline'
      - '--image'
      - 'gcr.io/$PROJECT_ID/dbt_meta_pipeline'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
    waitFor: ['Build dbt for Meta Pipeline']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy dbt Google Ads Pipeline'
    args:
      - run
      - deploy
      - 'dbt-google-ads-pipeline'
      - '--image'
      - 'gcr.io/$PROJECT_ID/dbt_google_ads_pipeline'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
    waitFor: ['Build dbt for Google Ads Pipeline']

substitutions:
  _ENVIRONMENT: 'dev'   # Can be overridden by Cloud Build triggers for different environments
  _PROJECT_ID: 'annular-net-436607-t0'

# Specify the images to be stored in Google Container Registry
images:
  - 'gcr.io/$PROJECT_ID/login_service'
  - 'gcr.io/$PROJECT_ID/ads_data_service'
  - 'gcr.io/$PROJECT_ID/meta_ingestion'
  - 'gcr.io/$PROJECT_ID/google_ads_ingestion'
  - 'gcr.io/$PROJECT_ID/dbt_meta_pipeline'
  - 'gcr.io/$PROJECT_ID/dbt_google_ads_pipeline'
