steps:
  # --- Build Ingestion Pipelines ---
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Google Ads Ingestion Pipeline'
    args: ['build', '-t', 'gcr.io/annular-net-436607-t0/google_ads_ingestion', './pipelines/google_ads_ingestion']
    waitFor: ['-']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Google Ads Ingestion Pipeline'
    args: ['push', 'gcr.io/annular-net-436607-t0/google_ads_ingestion']
    waitFor: ['Build Google Ads Ingestion Pipeline']

  # --- Deploy Pipelines to Cloud Run ---
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Deploy Google Ads Ingestion Pipeline'
    args:
      - 'run'
      - 'deploy'
      - 'google-ads-ingestion'
      - '--image'
      - 'gcr.io/annular-net-436607-t0/google_ads_ingestion'
      - '--platform'
      - 'managed'
      - '--region'
      - 'europe-west1'
      - '--service-account'
      - 'terraform-sa@annular-net-436607-t0.iam.gserviceaccount.com'
      - '--allow-unauthenticated'
    waitFor: ['Build Google Ads Ingestion Pipeline']

logsBucket: 'gs://annular-net-436607-t0-cloudbuild-logs'
serviceAccount: 'projects/annular-net-436607-t0/serviceAccounts/terraform-sa@annular-net-436607-t0.iam.gserviceaccount.com'

# Specify the images to be stored in Google Container Registry
images:
  - 'gcr.io/annular-net-436607-t0/google_ads_ingestion'
