steps:
  # Step 1: Build and Push login_service Docker Image


  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'gcr.io/annular-net-436607-t0/login-service', 
      './services/login_service/app'
    ]


  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/annular-net-436607-t0/login-service']

  # Step 2: Deploy login_service to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 
      'deploy', 
      'login-service',
      '--image', 'gcr.io/annular-net-436607-t0/login-service',
      '--platform', 'managed',
      '--region', 'europe-west1',
      '--service-account', "terraform-sa@annular-net-436607-t0.iam.gserviceaccount.com"
    ]


logsBucket: 'gs://annular-net-436607-t0-cloudbuild-logs'
serviceAccount: 'projects/annular-net-436607-t0/serviceAccounts/terraform-sa@annular-net-436607-t0.iam.gserviceaccount.com'