version: 2

sources:
  - name: raw
    schema: sample_ds
    tables:
      - name: raw_sample_ads   
        description: "This table contains raw Google Ads data."

      - name: advertisers_tracking  
        description: "This table contains advertiser IDs for tracking."

  - name: clean 
    schema: sample_ds
    tables:
      - name: clean_google_ads
        description: "This table contains clean Google Ads data."
