FROM alpine:latest
RUN apk add --no-cache openssl
WORKDIR /certs

CMD openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
    -keyout server.key -out server.crt \
    -subj "/C=US/ST=State/L=City/O=Organization/OU=Unit/CN=<Place tour VM external IP>" \
    -addext "subjectAltName = <Place tour VM external IP>" && \
    chmod 644 server.key && \
    chmod 644 server.crt