bigquery:
  project_id: "annular-net-436607-t0"
  tables:
    youtube_links: "annular-net-436607-t0.sample_ds.ad_urls_table"
    probable_youtube_links: "annular-net-436607-t0.sample_ds.ad_load_url_table"
    test_consumption: "annular-net-436607-t0.sample_ds.base_consume_google_ads"
 
concurrency:
  max_concurrent_tasks: 5
 
logging:
  log_level: INFO
 
shutdown:
  delay_seconds: 600  # 10 minutes